language: python
python:
  - "2.7"
before_install:
  - bash getdump.sh
script:
  - python listup_duplicates.py
before_deploy:
  - bash bin/before_deploy.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

branches:
  only:
    - master
