language: python
python:
  - "2.7"
before_install:
  - bash getdump.sh
before_script:
  - bash bin/before_script.sh
script:
  - python listup_duplicates.py
after_success:
  - bash bin/deploy.sh

branches:
  only:
    - master
