name: Playwright Tests

on:
  push:
    branches: [ master ]
    paths:
      - viewer/**
      - .github/workflows/playwright.yml

  pull_request:
    branches: [ master ]
    paths:
      - viewer/**
      - .github/workflows/playwright.yml

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version-file: ./viewer/.nvmrc
    - name: Install dependencies
      run: npm ci
      working-directory: ./viewer
    - name: Build for test
      run: |
        NODE_ENV=test npm run build
      working-directory: ./viewer
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
      working-directory: ./viewer
    - name: Run Playwright tests
      run: npm run e2e
      working-directory: ./viewer
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: viewer/playwright-report/
        retention-days: 30
