name: Ruff check

on:
  push:
    branches: [ master ]
    paths-ignore:
      - viewer/**
      - .github/workflows/update-viewer.yml
      - .github/workflows/playwright.yml

  pull_request:
    paths-ignore:
      - viewer/**
      - .github/workflows/update-viewer.yml
      - .github/workflows/playwright.yml

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install Ruff
        run: |
          uv tool install ruff

      - name: Lint
        run: |
          uv tool run ruff check --output-format=github

      - name: Format
        run: |
          uv tool run ruff format --diff
