name: Update viewer

on:
  push:
    branches: [ master ]
    paths:
      - viewer/**
      - .github/workflows/update-viewer.yml

  pull_request:
    paths:
      - viewer/**
      - .github/workflows/update-viewer.yml

jobs:
  build-viewer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: ./viewer/.nvmrc

      - run: |
          npm ci
          npm run check
          npm run build
          npm run lint
        working-directory: ./viewer

      - name: Upload artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./viewer/dist

  deploy-viewer:
    needs: build-viewer
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
