# This is a basic workflow to help you get started with Actions

name: Update

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths-ignore:
      - viewer/**
      - .github/workflows/update-viewer.yml
      - .github/workflows/playwright.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: "30 17 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: gist-update

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.10'

      - run: bash getdump.sh
      - run: python listup_duplicates.py -o duplicates.json dump_newest_only.txt

      - name: Upload to Gist
        run: |
          jq --raw-input --compact-output \
            '{ "files": { "duplicates.json": { "content": . } } }' \
            duplicates.json |
          curl --request PATCH \
            --url https://api.github.com/gists/${{ env.GIST_ID }} \
            --header 'authorization: token ${{ secrets.GIST_ACCESS_TOKEN }}' \
            --header 'accept: application/vnd.github.v3+json' \
            --header 'content-type: application/json' \
            --data-binary @- \
            --fail > /dev/null
        env:
          GIST_ID: cc8ec3b2d9a1cc63b39c8663328edfc6
