name: Update viewer

on:
  push:
    branches: [ master ]
    paths: [ viewer ]

jobs:
  update-viewer:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: |
          npm ci
          npm run build
          npm run lint
        working-directory: ./viewer

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./viewer/dist
