# This is a basic workflow to help you get started with Actions

name: Update

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths-ignore: [ viewer ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: "30 17 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: gist-update

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - run: bash getdump.sh
      - run: python listup_duplicates.py -o duplicates.json dump_newest_only.txt

      - name: Upload to Gist
        run: |
          gh auth login --with-token <<< '${{ secrets.GIST_ACCESS_TOKEN }}'
          gh gist edit '${{ env.GIST_ID }}' duplicates.json
        env:
          GIST_ID: cc8ec3b2d9a1cc63b39c8663328edfc6
